=== masaya87266/mybatis/src/main/java/com/masaya/mybatis/mybatis/parsing/mybatis-1-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT configuration (environment?, mappers?)>

        <!ELEMENT property EMPTY>
        <!ATTLIST property name CDATA #REQUIRED value CDATA #REQUIRED>

        <!ELEMENT environment (dataSource+)>
        <!ATTLIST environment default CDATA #REQUIRED>

        <!ELEMENT dataSource (property*)>
        <!ATTLIST dataSource id CDATA #REQUIRED>

        <!ELEMENT mappers (mapper*)>

        <!ELEMENT mapper EMPTY>
        <!ATTLIST mapper resource CDATA #IMPLIED>

        <!ELEMENT package EMPTY>
        <!ATTLIST package name CDATA #REQUIRED>

=== masaya87266/mybatis/src/main/resources/mybatis-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration
        SYSTEM
        "src/main/java/com/masaya/mybatis/mybatis/parsing/mybatis-1-config.dtd">
<configuration>

    <environment default="dev">
        <dataSource id="dev">
            <property name="driver" value="com.mysql.jdbc.Driver"/>
            <property name="url"
                      value="jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&amp;useUnicode=true&amp;characterEncoding=utf8&amp;rewriteBatchedStatements=true&amp;useSSL=false"/>
            <property name="username" value="root"/>
            <property name="password" value="zheng123"/>
        </dataSource>

        <dataSource id="test">
            <property name="driver" value="com.mysql.jdbc.Driver"/>
            <property name="url"
                      value="jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&amp;useUnicode=true&amp;characterEncoding=utf8&amp;rewriteBatchedStatements=true&amp;useSSL=false"/>
            <property name="username" value="root"/>
            <property name="password" value="zheng123"/>
        </dataSource>
    </environment>

    <mappers>
        <mapper resource="com/masaya/mybatis/mapper/UserInfoMapper.xml"/>
        <mapper resource="com/masaya/mybatis/mapper/OrderInfoMapper.xml"/>
    </mappers>
</configuration>
